### ISSUE TITLE
It says yarn command not found.

### ISSUE THREAD

**Issue by SEOSumit** [jokenox/Goopt#2]
I have written this "REACT_APP_OPENAI_API_KEY=my open api here"  to .env.local

Please guide me here.

1. how do I create a .env.local file
2. do I have to type REACT_APP_OPENAI_API_KEY=my open API here in the command line or create it manually. how?

just need information on this step. I am new to Github.

**Comment by jokenox** [comment]
You have to create it manually, create a file and name it ".env.local", make sure it doesn't have another extension, once you have created it, write in it the line with your OpenAI key.

I see you also need to install Yarn, or you can try to run it with npm.
