### ISSUE TITLE
It does not work anymore.

### ISSUE THREAD

**Issue by FormalSnake** [jokenox/Goopt#9]
I get unsafe request and openAI 500 errors.
Please fix.

**Comment by jokenox** [comment]
Apparently, the 500 error is due to problems on the OpenAI servers, because of the load by ChatGPT. I'll still see if something can be implemented to deal with this error and keep the program trying to get a response.

[https://platform.openai.com/docs/guides/error-codes/api-errors](url)

**Comment by FormalSnake** [comment]
> Apparently, the 500 error is due to problems on the OpenAI servers, because of the load by ChatGPT. I'll still see if something can be implemented to deal with this error and keep the program trying to get a response.
> 
> [https://platform.openai.com/docs/guides/error-codes/api-errors](url)

That's perfect!
The error makes sense, I tried changing the scripts to work with the official openai package, but that did not work.

**Comment by FormalSnake** [comment]
It works after a day of waiting
